apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: samplewebapi
    spec:
      containers:
      - name: samplewebapi
        image: dtcs/samplewebapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: samplewebapi
---
apiVersion: v1
kind: Service
metadata:
  name: samplewebapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: samplewebapi
